export const states_en = [
  {id: 1, name: 'Andhra Pradesh'},
  {id: 2, name: 'Arunachal Pradesh'},
  {id: 3, name: 'Assam'},
  {id: 4, name: 'Bihar'},
  {id: 5, name: 'Chhattisgarh'},
  {id: 6, name: 'Goa'},
  {id: 7, name: 'Gujarat'},
  {id: 8, name: 'Haryana'},
  {id: 9, name: 'Himachal Pradesh'},
  {id: 10, name: 'Jharkhand'},
  {id: 11, name: 'Karnataka'},
  {id: 12, name: 'Kerala'},
  {id: 13, name: 'Madhya Pradesh'},
  {id: 14, name: 'Maharashtra'},
  {id: 15, name: 'Manipur'},
  {id: 16, name: 'Meghalaya'},
  {id: 17, name: 'Mizoram'},
  {id: 18, name: 'Nagaland'},
  {id: 19, name: 'Odisha'},
  {id: 20, name: 'Punjab'},
  {id: 21, name: 'Rajasthan'},
  {id: 22, name: 'Sikkim'},
  {id: 23, name: 'Tamil Nadu'},
  {id: 24, name: 'Telangana'},
  {id: 25, name: 'Tripura'},
  {id: 26, name: 'Uttar Pradesh'},
  {id: 27, name: 'Uttarakhand'},
  {id: 28, name: 'West Bengal'},
];

export const cities_en = [
  {id: 1, name: 'Visakhapatnam', stateId: 1},
  {id: 2, name: 'Vijayawada', stateId: 1},
  {id: 3, name: 'Guntur', stateId: 1},
  {id: 4, name: 'Nellore', stateId: 1},
  {id: 5, name: 'Tirupati', stateId: 1},
  {id: 6, name: 'Kakinada', stateId: 1},
  {id: 7, name: 'Rajahmundry', stateId: 1},
  {id: 8, name: 'Kurnool', stateId: 1},
  {id: 9, name: 'Anantapur', stateId: 1},
  {id: 10, name: 'Warangal', stateId: 1},
  {id: 11, name: 'Itanagar', stateId: 2},
  {id: 12, name: 'Guwahati', stateId: 3},
  {id: 13, name: 'Dibrugarh', stateId: 3},
  {id: 14, name: 'Jorhat', stateId: 3},
  {id: 15, name: 'Silchar', stateId: 3},
  {id: 16, name: 'Tezpur', stateId: 3},
  {id: 17, name: 'Patna', stateId: 4},
  {id: 18, name: 'Gaya', stateId: 4},
  {id: 19, name: 'Bhagalpur', stateId: 4},
  {id: 20, name: 'Muzaffarpur', stateId: 4},
  {id: 21, name: 'Darbhanga', stateId: 4},
  {id: 22, name: 'Raipur', stateId: 5},
  {id: 23, name: 'Bhilai', stateId: 5},
  {id: 24, name: 'Bilaspur', stateId: 5},
  {id: 25, name: 'Korba', stateId: 5},
  {id: 26, name: 'Durg', stateId: 5},
  {id: 27, name: 'Panaji', stateId: 6},
  {id: 28, name: 'Vasco da Gama', stateId: 6},
  {id: 29, name: 'Margao', stateId: 6},
  {id: 30, name: 'Mapusa', stateId: 6},
  {id: 31, name: 'Ponda', stateId: 6},
  {id: 32, name: 'Ahmedabad', stateId: 7},
  {id: 33, name: 'Surat', stateId: 7},
  {id: 34, name: 'Vadodara', stateId: 7},
  {id: 35, name: 'Rajkot', stateId: 7},
  {id: 36, name: 'Gandhinagar', stateId: 7},
  {id: 37, name: 'Chandigarh', stateId: 8},
  {id: 38, name: 'Faridabad', stateId: 8},
  {id: 39, name: 'Gurugram', stateId: 8},
  {id: 40, name: 'Panipat', stateId: 8},
  {id: 41, name: 'Ambala', stateId: 8},
  {id: 42, name: 'Shimla', stateId: 9},
  {id: 43, name: 'Manali', stateId: 9},
  {id: 44, name: 'Dharamshala', stateId: 9},
  {id: 45, name: 'Solan', stateId: 9},
  {id: 46, name: 'Kullu', stateId: 9},
  {id: 47, name: 'Ranchi', stateId: 10},
  {id: 48, name: 'Jamshedpur', stateId: 10},
  {id: 49, name: 'Dhanbad', stateId: 10},
  {id: 50, name: 'Bokaro Steel City', stateId: 10},
  {id: 51, name: 'Deoghar', stateId: 10},
  {id: 52, name: 'Bengaluru', stateId: 11},
  {id: 53, name: 'Mysuru', stateId: 11},
  {id: 54, name: 'Hubballi', stateId: 11},
  {id: 55, name: 'Mangaluru', stateId: 11},
  {id: 56, name: 'Belagavi', stateId: 11},
  {id: 57, name: 'Thiruvananthapuram', stateId: 12},
  {id: 58, name: 'Kochi', stateId: 12},
  {id: 59, name: 'Kozhikode', stateId: 12},
  {id: 60, name: 'Thrissur', stateId: 12},
  {id: 61, name: 'Kollam', stateId: 12},
  {id: 62, name: 'Bhopal', stateId: 13},
  {id: 63, name: 'Indore', stateId: 13},
  {id: 64, name: 'Jabalpur', stateId: 13},
  {id: 65, name: 'Gwalior', stateId: 13},
  {id: 66, name: 'Ujjain', stateId: 13},
  {id: 67, name: 'Mumbai', stateId: 14},
  {id: 68, name: 'Pune', stateId: 14},
  {id: 69, name: 'Nagpur', stateId: 14},
  {id: 70, name: 'Nashik', stateId: 14},
  {id: 71, name: 'Thane', stateId: 14},
  {id: 72, name: 'Imphal', stateId: 15},
  {id: 73, name: 'Thoubal', stateId: 15},
  {id: 74, name: 'Bishnupur', stateId: 15},
  {id: 75, name: 'Kakching', stateId: 15},
  {id: 76, name: 'Senapati', stateId: 15},
  {id: 77, name: 'Shillong', stateId: 16},
  {id: 78, name: 'Tura', stateId: 16},
  {id: 79, name: 'Jowai', stateId: 16},
  {id: 80, name: 'Nongstoin', stateId: 16},
  {id: 81, name: 'Williamnagar', stateId: 16},
  {id: 82, name: 'Aizawl', stateId: 17},
  {id: 83, name: 'Lunglei', stateId: 17},
  {id: 84, name: 'Champhai', stateId: 17},
  {id: 85, name: 'Saiha', stateId: 17},
  {id: 86, name: 'Serchhip', stateId: 17},
  {id: 87, name: 'Kohima', stateId: 18},
  {id: 88, name: 'Dimapur', stateId: 18},
  {id: 89, name: 'Mokokchung', stateId: 18},
  {id: 90, name: 'Tuensang', stateId: 18},
  {id: 91, name: 'Wokha', stateId: 18},
  {id: 92, name: 'Bhubaneswar', stateId: 19},
  {id: 93, name: 'Cuttack', stateId: 19},
  {id: 94, name: 'Rourkela', stateId: 19},
  {id: 95, name: 'Brahmapur', stateId: 19},
  {id: 96, name: 'Sambalpur', stateId: 19},
  {id: 97, name: 'Amritsar', stateId: 20},
  {id: 98, name: 'Ludhiana', stateId: 20},
  {id: 99, name: 'Jalandhar', stateId: 20},
  {id: 100, name: 'Patiala', stateId: 20},
  {id: 101, name: 'Bathinda', stateId: 20},
  {id: 102, name: 'Jaipur', stateId: 21},
  {id: 103, name: 'Jodhpur', stateId: 21},
  {id: 104, name: 'Udaipur', stateId: 21},
  {id: 105, name: 'Kota', stateId: 21},
  {id: 106, name: 'Bikaner', stateId: 21},
  {id: 107, name: 'Gangtok', stateId: 22},
  {id: 108, name: 'Namchi', stateId: 22},
  {id: 109, name: 'Gyalshing', stateId: 22},
  {id: 110, name: 'Mangan', stateId: 22},
  {id: 111, name: 'Singtam', stateId: 22},
  {id: 112, name: 'Chennai', stateId: 23},
  {id: 113, name: 'Coimbatore', stateId: 23},
  {id: 114, name: 'Madurai', stateId: 23},
  {id: 115, name: 'Tiruchirappalli', stateId: 23},
  {id: 116, name: 'Salem', stateId: 23},
  {id: 117, name: 'Hyderabad', stateId: 24},
  {id: 118, name: 'Warangal', stateId: 24},
  {id: 119, name: 'Nizamabad', stateId: 24},
  {id: 120, name: 'Karimnagar', stateId: 24},
  {id: 121, name: 'Khammam', stateId: 24},
  {id: 122, name: 'Agartala', stateId: 25},
  {id: 123, name: 'Udaipur', stateId: 25},
  {id: 124, name: 'Dharmanagar', stateId: 25},
  {id: 125, name: 'Belonia', stateId: 25},
  {id: 126, name: 'Kailasahar', stateId: 25},
  {id: 127, name: 'Lucknow', stateId: 26},
  {id: 128, name: 'Kanpur', stateId: 26},
  {id: 129, name: 'Ghaziabad', stateId: 26},
  {id: 130, name: 'Agra', stateId: 26},
  {id: 131, name: 'Varanasi', stateId: 26},
  {id: 132, name: 'Dehradun', stateId: 27},
  {id: 133, name: 'Haridwar', stateId: 27},
  {id: 134, name: 'Rishikesh', stateId: 27},
  {id: 135, name: 'Nainital', stateId: 27},
  {id: 136, name: 'Mussoorie', stateId: 27},
  {id: 137, name: 'Kolkata', stateId: 28},
  {id: 138, name: 'Howrah', stateId: 28},
  {id: 139, name: 'Durgapur', stateId: 28},
  {id: 140, name: 'Asansol', stateId: 28},
  {id: 141, name: 'Siliguri', stateId: 28},
];
