export const states_hi = [
  {id: 1, name: 'आंध्र प्रदेश'},
  {id: 2, name: 'अरुणाचल प्रदेश'},
  {id: 3, name: 'असम'},
  {id: 4, name: 'बिहार'},
  {id: 5, name: 'छत्तीसगढ़'},
  {id: 6, name: 'गोवा'},
  {id: 7, name: 'गुजरात'},
  {id: 8, name: 'हरियाणा'},
  {id: 9, name: 'हिमाचल प्रदेश'},
  {id: 10, name: 'झारखंड'},
  {id: 11, name: 'कर्नाटक'},
  {id: 12, name: 'केरल'},
  {id: 13, name: 'मध्य प्रदेश'},
  {id: 14, name: 'महाराष्ट्र'},
  {id: 15, name: 'मणिपुर'},
  {id: 16, name: 'मेघालय'},
  {id: 17, name: 'मिजोरम'},
  {id: 18, name: 'नगालैंड'},
  {id: 19, name: 'ओडिशा'},
  {id: 20, name: 'पंजाब'},
  {id: 21, name: 'राजस्थान'},
  {id: 22, name: 'सिक्किम'},
  {id: 23, name: 'तमिलनाडु'},
  {id: 24, name: 'तेलंगाना'},
  {id: 25, name: 'त्रिपुरा'},
  {id: 26, name: 'उत्तर प्रदेश'},
  {id: 27, name: 'उत्तराखंड'},
  {id: 28, name: 'पश्चिम बंगाल'},
];

export const cities_hi = [
  {id: 1, name: 'विशाखापत्तनम', stateId: 1},
  {id: 2, name: 'विजयवाड़ा', stateId: 1},
  {id: 3, name: 'गुंटूर', stateId: 1},
  {id: 4, name: 'नेल्लोर', stateId: 1},
  {id: 5, name: 'तिरुपति', stateId: 1},
  {id: 6, name: 'काकीनाडा', stateId: 1},
  {id: 7, name: 'राजामुंदरी', stateId: 1},
  {id: 8, name: 'कुरनूल', stateId: 1},
  {id: 9, name: 'अनंतपुर', stateId: 1},
  {id: 10, name: 'वारंगल', stateId: 1},
  {id: 11, name: 'ईटानगर', stateId: 2},
  {id: 12, name: 'गुवाहाटी', stateId: 3},
  {id: 13, name: 'डिब्रूगढ़', stateId: 3},
  {id: 14, name: 'जोरहाट', stateId: 3},
  {id: 15, name: 'सिलचर', stateId: 3},
  {id: 16, name: 'तेज़पुर', stateId: 3},
  {id: 17, name: 'पटना', stateId: 4},
  {id: 18, name: 'गया', stateId: 4},
  {id: 19, name: 'भागलपुर', stateId: 4},
  {id: 20, name: 'मुजफ्फरपुर', stateId: 4},
  {id: 21, name: 'दरभंगा', stateId: 4},
  {id: 22, name: 'रायपुर', stateId: 5},
  {id: 23, name: 'भिलाई', stateId: 5},
  {id: 24, name: 'बिलासपुर', stateId: 5},
  {id: 25, name: 'कोरबा', stateId: 5},
  {id: 26, name: 'दुर्ग', stateId: 5},
  {id: 27, name: 'पणजी', stateId: 6},
  {id: 28, name: 'वास्को डा गामा', stateId: 6},
  {id: 29, name: 'मडगाँव', stateId: 6},
  {id: 30, name: 'मापुसा', stateId: 6},
  {id: 31, name: 'फोंडा', stateId: 6},
  {id: 32, name: 'अहमदाबाद', stateId: 7},
  {id: 33, name: 'सूरत', stateId: 7},
  {id: 34, name: 'वडोदरा', stateId: 7},
  {id: 35, name: 'राजकोट', stateId: 7},
  {id: 36, name: 'गांधीनगर', stateId: 7},
  {id: 37, name: 'चंडीगढ़', stateId: 8},
  {id: 38, name: 'फरीदाबाद', stateId: 8},
  {id: 39, name: 'गुरुग्राम', stateId: 8},
  {id: 40, name: 'पानीपत', stateId: 8},
  {id: 41, name: 'अंबाला', stateId: 8},
  {id: 42, name: 'शिमला', stateId: 9},
  {id: 43, name: 'मनाली', stateId: 9},
  {id: 44, name: 'धर्मशाला', stateId: 9},
  {id: 45, name: 'सोलन', stateId: 9},
  {id: 46, name: 'कुल्लू', stateId: 9},
  {id: 47, name: 'रांची', stateId: 10},
  {id: 48, name: 'जमशेदपुर', stateId: 10},
  {id: 49, name: 'धनबाद', stateId: 10},
  {id: 50, name: 'बोकारो स्टील सिटी', stateId: 10},
  {id: 51, name: 'देवघर', stateId: 10},
  {id: 52, name: 'बेंगलुरु', stateId: 11},
  {id: 53, name: 'मैसूर', stateId: 11},
  {id: 54, name: 'हुबली', stateId: 11},
  {id: 55, name: 'मंगलुरु', stateId: 11},
  {id: 56, name: 'बेलगावी', stateId: 11},
  {id: 57, name: 'तिरुवनंतपुरम', stateId: 12},
  {id: 58, name: 'कोच्चि', stateId: 12},
  {id: 59, name: 'कोझिकोड', stateId: 12},
  {id: 60, name: 'थ्रिसूर', stateId: 12},
  {id: 61, name: 'कोल्लम', stateId: 12},
  {id: 62, name: 'भोपाल', stateId: 13},
  {id: 63, name: 'इंदौर', stateId: 13},
  {id: 64, name: 'जबलपुर', stateId: 13},
  {id: 65, name: 'ग्वालियर', stateId: 13},
  {id: 66, name: 'उज्जैन', stateId: 13},
  {id: 67, name: 'मुंबई', stateId: 14},
  {id: 68, name: 'पुणे', stateId: 14},
  {id: 69, name: 'नागपुर', stateId: 14},
  {id: 70, name: 'नासिक', stateId: 14},
  {id: 71, name: 'ठाणे', stateId: 14},
  {id: 72, name: 'इंफाल', stateId: 15},
  {id: 73, name: 'थोबल', stateId: 15},
  {id: 74, name: 'बिष्णुपुर', stateId: 15},
  {id: 75, name: 'काकचिंग', stateId: 15},
  {id: 76, name: 'सेनापति', stateId: 15},
  {id: 77, name: 'शिलांग', stateId: 16},
  {id: 78, name: 'तुरा', stateId: 16},
  {id: 79, name: 'जवाई', stateId: 16},
  {id: 80, name: 'नोंगस्टोइन', stateId: 16},
  {id: 81, name: 'विलियमनगर', stateId: 16},
  {id: 82, name: 'ऐजोल', stateId: 17},
  {id: 83, name: 'लुंगलेई', stateId: 17},
  {id: 84, name: 'चम्फाई', stateId: 17},
  {id: 85, name: 'साइहा', stateId: 17},
  {id: 86, name: 'सर्सिम', stateId: 17},
  {id: 87, name: 'कोहिमा', stateId: 18},
  {id: 88, name: 'दीमापुर', stateId: 18},
  {id: 89, name: 'मोकोकचुंग', stateId: 18},
  {id: 90, name: 'तुन्सांग', stateId: 18},
  {id: 91, name: 'वोखा', stateId: 18},
  {id: 92, name: 'भुवनेश्वर', stateId: 19},
  {id: 93, name: 'कटक', stateId: 19},
  {id: 94, name: 'राउरकेला', stateId: 19},
  {id: 95, name: 'ब्रह्मपुर', stateId: 19},
  {id: 96, name: 'संबलपुर', stateId: 19},
  {id: 97, name: 'अमृतसर', stateId: 20},
  {id: 98, name: 'लुधियाना', stateId: 20},
  {id: 99, name: 'जालंधर', stateId: 20},
  {id: 100, name: 'पटियाला', stateId: 20},
  {id: 101, name: 'बठिंडा', stateId: 20},
  {id: 102, name: 'जयपुर', stateId: 21},
  {id: 103, name: 'जोधपुर', stateId: 21},
  {id: 104, name: 'उदयपुर', stateId: 21},
  {id: 105, name: 'कोटा', stateId: 21},
  {id: 106, name: 'बीकानेर', stateId: 21},
  {id: 107, name: 'गंगटोक', stateId: 22},
  {id: 108, name: 'नामची', stateId: 22},
  {id: 109, name: 'ग्यालशिंग', stateId: 22},
  {id: 110, name: 'माजंग', stateId: 22},
  {id: 111, name: 'सिंगताम', stateId: 22},
  {id: 112, name: 'चेन्नई', stateId: 23},
  {id: 113, name: 'कोयम्बटूर', stateId: 23},
  {id: 114, name: 'मदुरै', stateId: 23},
  {id: 115, name: 'तिरुचिरापल्ली', stateId: 23},
  {id: 116, name: 'सेलम', stateId: 23},
  {id: 117, name: 'हैदराबाद', stateId: 24},
  {id: 118, name: 'वारंगल', stateId: 24},
  {id: 119, name: 'निजामाबाद', stateId: 24},
  {id: 120, name: 'करीमनगर', stateId: 24},
  {id: 121, name: 'खम्मम', stateId: 24},
  {id: 122, name: 'अगरतला', stateId: 25},
  {id: 123, name: 'उदयपुर', stateId: 25},
  {id: 124, name: 'धर्मनगर', stateId: 25},
  {id: 125, name: 'बेलोनिया', stateId: 25},
  {id: 126, name: 'कैलाशहर', stateId: 25},
  {id: 127, name: 'लखनऊ', stateId: 26},
  {id: 128, name: 'कानपुर', stateId: 26},
  {id: 129, name: 'गाजियाबाद', stateId: 26},
  {id: 130, name: 'आगरा', stateId: 26},
  {id: 131, name: 'वाराणसी', stateId: 26},
  {id: 132, name: 'देहरादून', stateId: 27},
  {id: 133, name: 'हरिद्वार', stateId: 27},
  {id: 134, name: 'ऋषिकेश', stateId: 27},
  {id: 135, name: 'नैनीताल', stateId: 27},
  {id: 136, name: 'मसूरी', stateId: 27},
  {id: 137, name: 'कोलकाता', stateId: 28},
  {id: 138, name: 'हावड़ा', stateId: 28},
  {id: 139, name: 'दुर्गापुर', stateId: 28},
  {id: 140, name: 'आसनसोल', stateId: 28},
  {id: 141, name: 'सिलीगुड़ी', stateId: 28},
];
