export const states_pa = [
  {id: 1, name: 'ਆੰਧਰਾ ਪ੍ਰਦੇਸ਼'},
  {id: 2, name: 'ਅਰੁਣਾਚਲ ਪ੍ਰਦੇਸ਼'},
  {id: 3, name: 'ਅਸਮ'},
  {id: 4, name: 'ਬਿਹਾਰ'},
  {id: 5, name: 'ਛੱਤੀਸਗੜ੍ਹ'},
  {id: 6, name: 'ਗੋਆ'},
  {id: 7, name: 'ਗੁਜਰਾਤ'},
  {id: 8, name: 'ਹਰਿਆਣਾ'},
  {id: 9, name: 'ਹਿਮਾਚਲ ਪ੍ਰਦੇਸ਼'},
  {id: 10, name: 'ਝਾਰਖੰਡ'},
  {id: 11, name: 'ਕਰਨਾਟਕ'},
  {id: 12, name: 'ਕੇਰਲ'},
  {id: 13, name: 'ਮੱਧ ਪ੍ਰਦੇਸ਼'},
  {id: 14, name: 'ਮਹਾਰਾਸ਼ਟਰ'},
  {id: 15, name: 'ਮਣਿਪੁਰ'},
  {id: 16, name: 'ਮੇਘਾਲਿਆ'},
  {id: 17, name: 'ਮਿਜ਼ੋਰਮ'},
  {id: 18, name: 'ਨਾਗਾਲੈਂਡ'},
  {id: 19, name: 'ਓਡਿਸ਼ਾ'},
  {id: 20, name: 'ਪੰਜਾਬ'},
  {id: 21, name: 'ਰਾਜਸਥਾਨ'},
  {id: 22, name: 'ਸਿੱਕਿਮ'},
  {id: 23, name: 'ਤਮਿਲਨਾਡੂ'},
  {id: 24, name: 'ਤੇਲੰਗਾਨਾ'},
  {id: 25, name: 'ਤ੍ਰਿਪੁਰਾ'},
  {id: 26, name: 'ਉੱਤਰ ਪ੍ਰਦੇਸ਼'},
  {id: 27, name: 'ਉੱਤਰਾਖੰਡ'},
  {id: 28, name: 'ਪੱਛਮੀ ਬੰਗਾਲ'},
];

export const cities_pa = [
  {id: 1, name: 'ਵਿਸ਼ਾਖਾਪਟਣਮ', stateId: 1},
  {id: 2, name: 'ਵਿਜਯਵਾੜਾ', stateId: 1},
  {id: 3, name: 'ਗੁੰਟੂਰ', stateId: 1},
  {id: 4, name: 'ਨੇੱਲੋਰ', stateId: 1},
  {id: 5, name: 'ਤਿਰੁਪਤੀ', stateId: 1},
  {id: 6, name: 'ਕਾਕੀਨਾਡਾ', stateId: 1},
  {id: 7, name: 'ਰਾਜਮੁੰਦਰੀ', stateId: 1},
  {id: 8, name: 'ਕੁਰਨੂਲ', stateId: 1},
  {id: 9, name: 'ਅਨੰਤਪੁਰ', stateId: 1},
  {id: 10, name: 'ਵਾਰੰਗਲ', stateId: 1},
  {id: 11, name: 'ਈਟਾਨਗਰ', stateId: 2},
  {id: 12, name: 'ਗੁਹਾਟੀ', stateId: 3},
  {id: 13, name: 'ਡੀਬਰੂਗੜ', stateId: 3},
  {id: 14, name: 'ਜੋਰਹਾਟ', stateId: 3},
  {id: 15, name: 'ਸਿਲਚਰ', stateId: 3},
  {id: 16, name: 'ਤਿਜ਼ਪੁਰ', stateId: 3},
  {id: 17, name: 'ਪਟਨਾ', stateId: 4},
  {id: 18, name: 'ਗਿਆ', stateId: 4},
  {id: 19, name: 'ਭਾਗਲਪੁਰ', stateId: 4},
  {id: 20, name: 'ਮੁਜ਼ਫਰਪੁਰ', stateId: 4},
  {id: 21, name: 'ਦਰਭੰਗਾ', stateId: 4},
  {id: 22, name: 'ਰਾਇਪੁਰ', stateId: 5},
  {id: 23, name: 'ਭਿਲਾਈ', stateId: 5},
  {id: 24, name: 'ਬਿਲਾਸਪੁਰ', stateId: 5},
  {id: 25, name: 'ਕੋਰਬਾ', stateId: 5},
  {id: 26, name: 'ਦੁਰਗ', stateId: 5},
  {id: 27, name: 'ਪਨਜੀ', stateId: 6},
  {id: 28, name: 'ਵਾਸਕੋ ਡਾ ਗਾਮਾ', stateId: 6},
  {id: 29, name: 'ਮਦਗਾਓ', stateId: 6},
  {id: 30, name: 'ਮਾਪਸਾ', stateId: 6},
  {id: 31, name: 'ਫੋੰਡਾ', stateId: 6},
  {id: 32, name: 'ਅਹਿਮਦਾਬਾਦ', stateId: 7},
  {id: 33, name: 'ਸੂਰਤ', stateId: 7},
  {id: 34, name: 'ਵਡੋਦਰਾ', stateId: 7},
  {id: 35, name: 'ਰਾਜਕੋਟ', stateId: 7},
  {id: 36, name: 'ਗੰਧੀਨਗਰ', stateId: 7},
  {id: 37, name: 'ਚੰਡੀਗੜ੍ਹ', stateId: 8},
  {id: 38, name: 'ਫਰੀਦਾਬਾਦ', stateId: 8},
  {id: 39, name: 'ਗੁੜਗਾਂਵ', stateId: 8},
  {id: 40, name: 'ਪਾਣੀਪਤ', stateId: 8},
  {id: 41, name: 'ਅੰਬਾਲਾ', stateId: 8},
  {id: 42, name: 'ਸ਼ਿਮਲਾ', stateId: 9},
  {id: 43, name: 'ਮਨਾਲੀ', stateId: 9},
  {id: 44, name: 'ਧਰਮਸ਼ਾਲਾ', stateId: 9},
  {id: 45, name: 'ਸੋਲਨ', stateId: 9},
  {id: 46, name: 'ਕੁੱਲੂ', stateId: 9},
  {id: 47, name: 'ਰਾਂਚੀ', stateId: 10},
  {id: 48, name: 'ਜਮਸ਼ੇਦਪੁਰ', stateId: 10},
  {id: 49, name: 'ਧਨਬਾਦ', stateId: 10},
  {id: 50, name: 'ਬੋਕਾਰੋ ਸਟੀਲ ਸਿਟੀ', stateId: 10},
  {id: 51, name: 'ਦੇਵਘਰ', stateId: 10},
  {id: 52, name: 'ਬੈਂਗਲੁਰੂ', stateId: 11},
  {id: 53, name: 'ਮੈਸੂਰ', stateId: 11},
  {id: 54, name: 'ਹੁਬਲੀ', stateId: 11},
  {id: 55, name: 'ਮੰਗਲੌਰ', stateId: 11},
  {id: 56, name: 'ਬੇਲਗਾਵੀ', stateId: 11},
  {id: 57, name: 'ਤਿਰੁਵਨੰਤਪੁਰਮ', stateId: 12},
  {id: 58, name: 'ਕੋਚੀ', stateId: 12},
  {id: 59, name: 'ਕੋਜ਼ੀਕੋਡ', stateId: 12},
  {id: 60, name: 'ਥਰਿਸ਼ੂਰ', stateId: 12},
  {id: 61, name: 'ਕੋਲਮ', stateId: 12},
  {id: 62, name: 'ਭੋਪਾਲ', stateId: 13},
  {id: 63, name: 'ਇੰਦੌਰ', stateId: 13},
  {id: 64, name: 'ਜਬਲਪੁਰ', stateId: 13},
  {id: 65, name: 'ਗਵਾਲਿਯਰ', stateId: 13},
  {id: 66, name: 'ਉੱਜੈਨ', stateId: 13},
  {id: 67, name: 'ਮੁੰਬਈ', stateId: 14},
  {id: 68, name: 'ਪੂਨੇ', stateId: 14},
  {id: 69, name: 'ਨਾਗਪੁਰ', stateId: 14},
  {id: 70, name: 'ਨਾਸ਼ਿਕ', stateId: 14},
  {id: 71, name: 'ਠਾਣੇ', stateId: 14},
  {id: 72, name: 'ਇੰਫਾਲ', stateId: 15},
  {id: 73, name: 'ਥੌਬਲ', stateId: 15},
  {id: 74, name: 'ਬਿਸ਼ਨੁਪੁਰ', stateId: 15},
  {id: 75, name: 'ਕਾਕਚਿੰਗ', stateId: 15},
  {id: 76, name: 'ਸੇਨਾਪਤੀ', stateId: 15},
  {id: 77, name: 'ਸ਼ਿਲੋਂਗ', stateId: 16},
  {id: 78, name: 'ਤੁਰਾ', stateId: 16},
  {id: 79, name: 'ਜਵਾਈ', stateId: 16},
  {id: 80, name: 'ਨੋਂਗਸਟੋਇਨ', stateId: 16},
  {id: 81, name: 'ਵਿਲੀਅਮਨਗਰ', stateId: 16},
  {id: 82, name: 'ਅਈਜ਼ੌਲ', stateId: 17},
  {id: 83, name: 'ਲੁੰਗਲੇਈ', stateId: 17},
  {id: 84, name: 'ਚੰਪਾਈ', stateId: 17},
  {id: 85, name: 'ਸੈਹਾ', stateId: 17},
  {id: 86, name: 'ਸਰਸਿਂਗ', stateId: 17},
  {id: 87, name: 'ਕੋਹੀਮਾ', stateId: 18},
  {id: 88, name: 'ਦੀਮਾਪੁਰ', stateId: 18},
  {id: 89, name: 'ਮੋਕੋਕਚੁੰਗ', stateId: 18},
  {id: 90, name: 'ਤੁਨਸੰਗ', stateId: 18},
  {id: 91, name: 'ਵੋਕਾ', stateId: 18},
  {id: 92, name: 'ਭੁਵਨੇਸ਼ਵਰ', stateId: 19},
  {id: 93, name: 'ਕਟਕ', stateId: 19},
  {id: 94, name: 'ਰਾਉਰਕੇਲਾ', stateId: 19},
  {id: 95, name: 'ਬ੍ਰਹਮਪੁਰ', stateId: 19},
  {id: 96, name: 'ਸੰਬਲਪੁਰ', stateId: 19},
  {id: 97, name: 'ਅੰਮ੍ਰਿਤਸਰ', stateId: 20},
  {id: 98, name: 'ਲੁਧਿਆਣਾ', stateId: 20},
  {id: 99, name: 'ਜਲੰਧਰ', stateId: 20},
  {id: 100, name: 'ਪਟਿਆਲਾ', stateId: 20},
  {id: 101, name: 'ਬਠਿੰਡਾ', stateId: 20},
  {id: 102, name: 'ਜੈਪੁਰ', stateId: 21},
  {id: 103, name: 'ਜੋਧਪੁਰ', stateId: 21},
  {id: 104, name: 'ਉਦੈਪੁਰ', stateId: 21},
  {id: 105, name: 'ਕੋਟਾ', stateId: 21},
  {id: 106, name: 'ਬੀਕਾਨੇਰ', stateId: 21},
  {id: 107, name: 'ਗਾਂਗਟੋਕ', stateId: 22},
  {id: 108, name: 'ਨਮਚੀ', stateId: 22},
  {id: 109, name: 'ਗਿਆਲਸਿੰਗ', stateId: 22},
  {id: 110, name: 'ਮਾਜਾਂਗ', stateId: 22},
  {id: 111, name: 'ਸਿੰਗਟਮ', stateId: 22},
  {id: 112, name: 'ਚੇਨਈ', stateId: 23},
  {id: 113, name: 'ਕੋਇਮਬਤੂਰ', stateId: 23},
  {id: 114, name: 'ਮਦੁਰਾਈ', stateId: 23},
  {id: 115, name: 'ਤਿਰੁਚਿਰਾਪੱਲੀ', stateId: 23},
  {id: 116, name: 'ਸੇਲਮ', stateId: 23},
  {id: 117, name: 'ਹੈਦਰਾਬਾਦ', stateId: 24},
  {id: 118, name: 'ਵਾਰੰਗਲ', stateId: 24},
  {id: 119, name: 'ਨਿਜ਼ਾਮਾਬਾਦ', stateId: 24},
  {id: 120, name: 'ਕਰੀਮਨਗਰ', stateId: 24},
  {id: 121, name: 'ਖਮਮ', stateId: 24},
  {id: 122, name: 'ਅਗਰਤਲਾ', stateId: 25},
  {id: 123, name: 'ਉਦੈਪੁਰ', stateId: 25},
  {id: 124, name: 'ਧਰਮਨਗਰ', stateId: 25},
  {id: 125, name: 'ਬੇਲੋਨੀਆ', stateId: 25},
  {id: 126, name: 'ਕੈਲਾਸਹਰ', stateId: 25},
  {id: 127, name: 'ਲਖਨਊ', stateId: 26},
  {id: 128, name: 'ਕਾਨਪੁਰ', stateId: 26},
  {id: 129, name: 'ਗਾਜੀਆਬਾਦ', stateId: 26},
  {id: 130, name: 'ਆਗਰਾ', stateId: 26},
  {id: 131, name: 'ਵਾਰਾਨਸੀ', stateId: 26},
  {id: 132, name: 'ਦੇਹਰਾਦੂਨ', stateId: 27},
  {id: 133, name: 'ਹਰਿਦੁਆਰ', stateId: 27},
  {id: 134, name: 'ਰਿਸ਼ੀਕੇਸ਼', stateId: 27},
  {id: 135, name: 'ਨੈਨੀਤਾਲ', stateId: 27},
  {id: 136, name: 'ਮਸੂਰੀ', stateId: 27},
  {id: 137, name: 'ਕੋਲਕਾਤਾ', stateId: 28},
  {id: 138, name: 'ਹਾਵੜਾ', stateId: 28},
  {id: 139, name: 'ਦੁਰਗਾਪੁਰ', stateId: 28},
  {id: 140, name: 'ਆਸਨਸੋਲ', stateId: 28},
  {id: 141, name: 'ਸਿਲਿਗੁੜੀ', stateId: 28},
];
