export const states_ta = [
  {id: 1, name: 'ஆந்திரா பிரதேசம்'},
  {id: 2, name: 'அருணாச்சல பிரதேசம்'},
  {id: 3, name: 'அசாம்'},
  {id: 4, name: 'பிகார்'},
  {id: 5, name: 'சத்தீஸ்கர்'},
  {id: 6, name: 'கோவா'},
  {id: 7, name: 'குஜராத்'},
  {id: 8, name: 'ஹரியானா'},
  {id: 9, name: 'இமாச்சல் பிரதேசம்'},
  {id: 10, name: 'ஜார்கண்ட்'},
  {id: 11, name: 'கர்நாடகா'},
  {id: 12, name: 'கேரளா'},
  {id: 13, name: 'மத்திய பிரதேசம்'},
  {id: 14, name: 'மகாராஷ்டிரா'},
  {id: 15, name: 'மணிப்பூர்'},
  {id: 16, name: 'மேகாலயா'},
  {id: 17, name: 'மிசோராம்'},
  {id: 18, name: 'நாகாலாந்து'},
  {id: 19, name: 'ஒடிசா'},
  {id: 20, name: 'பஞ்சாப்'},
  {id: 21, name: 'ராஜஸ்தான்'},
  {id: 22, name: 'சிக்கிம்'},
  {id: 23, name: 'தமிழ் நாடு'},
  {id: 24, name: 'தெலுங்கானா'},
  {id: 25, name: 'திரிபுரா'},
  {id: 26, name: 'உத்தரப்பிரதேசம்'},
  {id: 27, name: 'உத்தரகாண்ட்'},
  {id: 28, name: 'மேற்கு வங்காளம்'},
];

export const cities_ta = [
  {id: 1, name: 'விசாகப்பட்டினம்', stateId: 1},
  {id: 2, name: 'விஜயவாடா', stateId: 1},
  {id: 3, name: 'குந்தூர்', stateId: 1},
  {id: 4, name: 'நெல்லூர்', stateId: 1},
  {id: 5, name: 'திருப்பதி', stateId: 1},
  {id: 6, name: 'காகிநாடா', stateId: 1},
  {id: 7, name: 'ராஜமுந்த்ரி', stateId: 1},
  {id: 8, name: 'குர்னூல்', stateId: 1},
  {id: 9, name: 'அனந்தபூர்', stateId: 1},
  {id: 10, name: 'வரங்கல்', stateId: 1},
  {id: 11, name: 'இடனகர்', stateId: 2},
  {id: 12, name: 'குவஹாட்டி', stateId: 3},
  {id: 13, name: 'திபுருகர்', stateId: 3},
  {id: 14, name: 'ஜோர்ஹாட்', stateId: 3},
  {id: 15, name: 'சில்சார்', stateId: 3},
  {id: 16, name: 'தெஸ்பூர்', stateId: 3},
  {id: 17, name: 'பட்னா', stateId: 4},
  {id: 18, name: 'கயா', stateId: 4},
  {id: 19, name: 'பகல்பூர்', stateId: 4},
  {id: 20, name: 'முசாபர்பூர்', stateId: 4},
  {id: 21, name: 'தர்பhanga', stateId: 4},
  {id: 22, name: 'ராய்பூர்', stateId: 5},
  {id: 23, name: 'பிலாய்', stateId: 5},
  {id: 24, name: 'பிலாஸ்பூர்', stateId: 5},
  {id: 25, name: 'கோர்பா', stateId: 5},
  {id: 26, name: 'துர்க்', stateId: 5},
  {id: 27, name: 'பனாஜி', stateId: 6},
  {id: 28, name: 'வாஸ்கோ டா காமா', stateId: 6},
  {id: 29, name: 'மார்கோ', stateId: 6},
  {id: 30, name: 'மாபுசா', stateId: 6},
  {id: 31, name: 'பொண்டா', stateId: 6},
  {id: 32, name: 'அகமதாபாத்', stateId: 7},
  {id: 33, name: 'சூரத்', stateId: 7},
  {id: 34, name: 'வடோதரா', stateId: 7},
  {id: 35, name: 'ராஜ்கோட்', stateId: 7},
  {id: 36, name: 'காந்திநகர்', stateId: 7},
  {id: 37, name: 'சண்டிகார்', stateId: 8},
  {id: 38, name: 'பரிதாபாத்', stateId: 8},
  {id: 39, name: 'குருகிராம்', stateId: 8},
  {id: 40, name: 'பனிபட்', stateId: 8},
  {id: 41, name: 'அம்பாலா', stateId: 8},
  {id: 42, name: 'சிம்லா', stateId: 9},
  {id: 43, name: 'மணாலி', stateId: 9},
  {id: 44, name: 'தரமசாலா', stateId: 9},
  {id: 45, name: 'சோலான்', stateId: 9},
  {id: 46, name: 'குள்ளு', stateId: 9},
  {id: 47, name: 'ராஞ்சி', stateId: 10},
  {id: 48, name: 'ஜம்ஷெட்பூர்', stateId: 10},
  {id: 49, name: 'தனபாட்', stateId: 10},
  {id: 50, name: 'போகாரோ ஸ்டீல் சிட்டி', stateId: 10},
  {id: 51, name: 'தேவகார்', stateId: 10},
  {id: 52, name: 'பெங்களூர்', stateId: 11},
  {id: 53, name: 'மிஸூரு', stateId: 11},
  {id: 54, name: 'ஹுப்ளி', stateId: 11},
  {id: 55, name: 'மங்களூர்', stateId: 11},
  {id: 56, name: 'பெல்காவி', stateId: 11},
  {id: 57, name: 'திருவனந்தபுரம்', stateId: 12},
  {id: 58, name: 'கொச்சி', stateId: 12},
  {id: 59, name: 'கொசிகோடு', stateId: 12},
  {id: 60, name: 'திருச்சூர்', stateId: 12},
  {id: 61, name: 'கொல்லம்', stateId: 12},
  {id: 62, name: 'போபால்', stateId: 13},
  {id: 63, name: 'இந்தோர்', stateId: 13},
  {id: 64, name: 'ஜபல்பூர்', stateId: 13},
  {id: 65, name: 'குவாலியார்', stateId: 13},
  {id: 66, name: 'உஜ்ஜைன்', stateId: 13},
  {id: 67, name: 'மும்பை', stateId: 14},
  {id: 68, name: 'புனே', stateId: 14},
  {id: 69, name: 'நாக்பூர்', stateId: 14},
  {id: 70, name: 'நாசிக்', stateId: 14},
  {id: 71, name: 'தானே', stateId: 14},
  {id: 72, name: 'இம்பால்', stateId: 15},
  {id: 73, name: 'தூபல்', stateId: 15},
  {id: 74, name: 'பிஷ்ணுபூர்', stateId: 15},
  {id: 75, name: 'கக்க்சிங்', stateId: 15},
  {id: 76, name: 'செனபட்டி', stateId: 15},
  {id: 77, name: 'ஷில்லோங்', stateId: 16},
  {id: 78, name: 'துரா', stateId: 16},
  {id: 79, name: 'ஜோவை', stateId: 16},
  {id: 80, name: 'நோங்ஸ்டோன்', stateId: 16},
  {id: 81, name: 'வில்லியம்நகர்', stateId: 16},
  {id: 82, name: 'ஐசோல்', stateId: 17},
  {id: 83, name: 'லங்க்லேய்', stateId: 17},
  {id: 84, name: 'சாம்பாய்', stateId: 17},
  {id: 85, name: 'சாயா', stateId: 17},
  {id: 86, name: 'செர்சிப்', stateId: 17},
  {id: 87, name: 'கோஹிமா', stateId: 18},
  {id: 88, name: 'திமாபூர்', stateId: 18},
  {id: 89, name: 'மோகோக்குங்', stateId: 18},
  {id: 90, name: 'துவேன்சாங்', stateId: 18},
  {id: 91, name: 'வோக்கா', stateId: 18},
  {id: 92, name: 'புவனேஸ்வர்', stateId: 19},
  {id: 93, name: 'கட்டாக்', stateId: 19},
  {id: 94, name: 'ரூர்க்கேலா', stateId: 19},
  {id: 95, name: 'பிரம்மாபூர்', stateId: 19},
  {id: 96, name: 'சம்பல்பூர்', stateId: 19},
  {id: 97, name: 'அம்ரித்சர்', stateId: 20},
  {id: 98, name: 'லூதியானா', stateId: 20},
  {id: 99, name: 'ஜலந்தர்', stateId: 20},
  {id: 100, name: 'பட்டியாலா', stateId: 20},
  {id: 101, name: 'படிந்தா', stateId: 20},
  {id: 102, name: 'ஜெய்ப்பூர்', stateId: 21},
  {id: 103, name: 'ஜோத்பூர்', stateId: 21},
  {id: 104, name: 'உடைப்பூர்', stateId: 21},
  {id: 105, name: 'கோத்தா', stateId: 21},
  {id: 106, name: 'பிகனேர்', stateId: 21},
  {id: 107, name: 'காங்டாக்', stateId: 22},
  {id: 108, name: 'நம்சி', stateId: 22},
  {id: 109, name: 'க்யால்ஷிங்', stateId: 22},
  {id: 110, name: 'மான்ஜங்', stateId: 22},
  {id: 111, name: 'சிங்க்டாம்', stateId: 22},
  {id: 112, name: 'சென்னை', stateId: 23},
  {id: 113, name: 'கோயம்புத்தூர்', stateId: 23},
  {id: 114, name: 'மதுரை', stateId: 23},
  {id: 115, name: 'திருச்சிராப்பள்ளி', stateId: 23},
  {id: 116, name: 'சேலம்', stateId: 23},
  {id: 117, name: 'ஹைதராபாத்', stateId: 24},
  {id: 118, name: 'வரங்கல்', stateId: 24},
  {id: 119, name: 'நிஸாமாபாத்', stateId: 24},
  {id: 120, name: 'கரிம்நகர்', stateId: 24},
  {id: 121, name: 'கம்மம்', stateId: 24},
  {id: 122, name: 'அகார்தலா', stateId: 25},
  {id: 123, name: 'உதயபூர்', stateId: 25},
  {id: 124, name: 'தர்மநகர்', stateId: 25},
  {id: 125, name: 'பெலோனியா', stateId: 25},
  {id: 126, name: 'கைலாசஹர்', stateId: 25},
  {id: 127, name: 'லக்னோ', stateId: 26},
  {id: 128, name: 'கான்பூர்', stateId: 26},
  {id: 129, name: 'காசியாபாத்', stateId: 26},
  {id: 130, name: 'ஆக்ரா', stateId: 26},
  {id: 131, name: 'வாரணாசி', stateId: 26},
  {id: 132, name: 'டேராடூன்', stateId: 27},
  {id: 133, name: 'ஹரித்வார்', stateId: 27},
  {id: 134, name: 'ரிஷிகேஷ்', stateId: 27},
  {id: 135, name: 'நைனிடால்', stateId: 27},
  {id: 136, name: 'மசூரி', stateId: 27},
  {id: 137, name: 'கொல்கத்தா', stateId: 28},
  {id: 138, name: 'ஹாவ்ரா', stateId: 28},
  {id: 139, name: 'துர்காபூர்', stateId: 28},
  {id: 140, name: 'ஆசன்சோல்', stateId: 28},
  {id: 141, name: 'சிலிகுரி', stateId: 28},
];
