export const states_ur = [
  {id: 1, name: 'آندھرا پردیش'},
  {id: 2, name: 'اروناچل پردیش'},
  {id: 3, name: 'آسام'},
  {id: 4, name: 'بہار'},
  {id: 5, name: 'چھتیس گڑھ'},
  {id: 6, name: 'گوا'},
  {id: 7, name: 'گجرات'},
  {id: 8, name: 'ہریانہ'},
  {id: 9, name: 'ہماچل پردیش'},
  {id: 10, name: 'جھارکھنڈ'},
  {id: 11, name: 'کرناٹک'},
  {id: 12, name: 'کیرالہ'},
  {id: 13, name: 'مدھیہ پردیش'},
  {id: 14, name: 'مہاراشٹر'},
  {id: 15, name: 'منی پور'},
  {id: 16, name: 'میگھالیہ'},
  {id: 17, name: 'میزورم'},
  {id: 18, name: 'ناگالینڈ'},
  {id: 19, name: 'اوڈیشا'},
  {id: 20, name: 'پنجاب'},
  {id: 21, name: 'راجستھان'},
  {id: 22, name: 'سکم'},
  {id: 23, name: 'تمل ناڈو'},
  {id: 24, name: 'تلنگانہ'},
  {id: 25, name: 'تریپورہ'},
  {id: 26, name: 'اتر پردیش'},
  {id: 27, name: 'اتراکھنڈ'},
  {id: 28, name: 'مغربی بنگال'},
];

export const cities_ur = [
  {id: 1, name: 'وشاکھاپٹنم', stateId: 1},
  {id: 2, name: 'وجےواڑا', stateId: 1},
  {id: 3, name: 'گنٹور', stateId: 1},
  {id: 4, name: 'نیلور', stateId: 1},
  {id: 5, name: 'ترپتی', stateId: 1},
  {id: 6, name: 'کاکناڈا', stateId: 1},
  {id: 7, name: 'راجہمندری', stateId: 1},
  {id: 8, name: 'کرنول', stateId: 1},
  {id: 9, name: 'اننتپر', stateId: 1},
  {id: 10, name: 'وارنگل', stateId: 1},
  {id: 11, name: 'ایٹنگر', stateId: 2},
  {id: 12, name: 'گواہاٹی', stateId: 3},
  {id: 13, name: 'دبروگرہ', stateId: 3},
  {id: 14, name: 'جوہاٹ', stateId: 3},
  {id: 15, name: 'سلچر', stateId: 3},
  {id: 16, name: 'ٹیزپور', stateId: 3},
  {id: 17, name: 'پٹنہ', stateId: 4},
  {id: 18, name: 'گیا', stateId: 4},
  {id: 19, name: 'بھاگالپر', stateId: 4},
  {id: 20, name: 'مظفرپر', stateId: 4},
  {id: 21, name: 'دربھنگا', stateId: 4},
  {id: 22, name: 'رائپر', stateId: 5},
  {id: 23, name: 'بھلائی', stateId: 5},
  {id: 24, name: 'بلاسپر', stateId: 5},
  {id: 25, name: 'کوربا', stateId: 5},
  {id: 26, name: 'درگ', stateId: 5},
  {id: 27, name: 'پناجی', stateId: 6},
  {id: 28, name: 'واسکو دہ گاما', stateId: 6},
  {id: 29, name: 'مرگاؤ', stateId: 6},
  {id: 30, name: 'مپوسا', stateId: 6},
  {id: 31, name: 'پونڈا', stateId: 6},
  {id: 32, name: 'احمدآباد', stateId: 7},
  {id: 33, name: 'سورت', stateId: 7},
  {id: 34, name: 'وادودرہ', stateId: 7},
  {id: 35, name: 'راجکوٹ', stateId: 7},
  {id: 36, name: 'گاندھینگر', stateId: 7},
  {id: 37, name: 'چندی گڑھ', stateId: 8},
  {id: 38, name: 'فریدآباد', stateId: 8},
  {id: 39, name: 'گرگاؤں', stateId: 8},
  {id: 40, name: 'پانیپت', stateId: 8},
  {id: 41, name: 'امبالہ', stateId: 8},
  {id: 42, name: 'شملہ', stateId: 9},
  {id: 43, name: 'منالی', stateId: 9},
  {id: 44, name: 'دھرمشالہ', stateId: 9},
  {id: 45, name: 'سولن', stateId: 9},
  {id: 46, name: 'کلو', stateId: 9},
  {id: 47, name: 'رانچی', stateId: 10},
  {id: 48, name: 'جمشیدپور', stateId: 10},
  {id: 49, name: 'دھنباد', stateId: 10},
  {id: 50, name: 'بوکارو سٹی', stateId: 10},
  {id: 51, name: 'دیوگھر', stateId: 10},
  {id: 52, name: 'بینگلورو', stateId: 11},
  {id: 53, name: 'میسور', stateId: 11},
  {id: 54, name: 'ہبلی', stateId: 11},
  {id: 55, name: 'منگلور', stateId: 11},
  {id: 56, name: 'بیلگاوی', stateId: 11},
  {id: 57, name: 'تھروونانتھپورم', stateId: 12},
  {id: 58, name: 'کوچی', stateId: 12},
  {id: 59, name: 'کوزہیکوڈ', stateId: 12},
  {id: 60, name: 'تریشور', stateId: 12},
  {id: 61, name: 'کولام', stateId: 12},
  {id: 62, name: 'بھوپال', stateId: 13},
  {id: 63, name: 'اندور', stateId: 13},
  {id: 64, name: 'جبلپور', stateId: 13},
  {id: 65, name: 'گوالیئر', stateId: 13},
  {id: 66, name: 'اجین', stateId: 13},
  {id: 67, name: 'ممبئی', stateId: 14},
  {id: 68, name: 'پونہ', stateId: 14},
  {id: 69, name: 'ناگپور', stateId: 14},
  {id: 70, name: 'ناشک', stateId: 14},
  {id: 71, name: 'ٹھانے', stateId: 14},
  {id: 72, name: 'امفال', stateId: 15},
  {id: 73, name: 'تھوبال', stateId: 15},
  {id: 74, name: 'بشنوپور', stateId: 15},
  {id: 75, name: 'کاکچنگ', stateId: 15},
  {id: 76, name: 'سیناپٹی', stateId: 15},
  {id: 77, name: 'شلنگ', stateId: 16},
  {id: 78, name: 'ٹورا', stateId: 16},
  {id: 79, name: 'جوئی', stateId: 16},
  {id: 80, name: 'نونگسٹوئن', stateId: 16},
  {id: 81, name: 'ویلیمنگر', stateId: 16},
  {id: 82, name: 'ایزول', stateId: 17},
  {id: 83, name: 'لنگلی', stateId: 17},
  {id: 84, name: 'چمپائی', stateId: 17},
  {id: 85, name: 'سائہا', stateId: 17},
  {id: 86, name: 'سرچھپ', stateId: 17},
  {id: 87, name: 'کوہیما', stateId: 18},
  {id: 88, name: 'دیماپور', stateId: 18},
  {id: 89, name: 'موکوکچنگ', stateId: 18},
  {id: 90, name: 'تینسانگ', stateId: 18},
  {id: 91, name: 'ووکھا', stateId: 18},
  {id: 92, name: 'بھوبنیشور', stateId: 19},
  {id: 93, name: 'کٹک', stateId: 19},
  {id: 94, name: 'روڑکیلا', stateId: 19},
  {id: 95, name: 'برہمپور', stateId: 19},
  {id: 96, name: 'سمبلپور', stateId: 19},
  {id: 97, name: 'امرتسر', stateId: 20},
  {id: 98, name: 'لدھیانہ', stateId: 20},
  {id: 99, name: 'جالندھر', stateId: 20},
  {id: 100, name: 'پٹیالہ', stateId: 20},
  {id: 101, name: 'بٹھنڈہ', stateId: 20},
  {id: 102, name: 'جیپور', stateId: 21},
  {id: 103, name: 'جودھپور', stateId: 21},
  {id: 104, name: 'اودیپور', stateId: 21},
  {id: 105, name: 'کوٹا', stateId: 21},
  {id: 106, name: 'بکانیر', stateId: 21},
  {id: 107, name: 'گینگٹوک', stateId: 22},
  {id: 108, name: 'نمچی', stateId: 22},
  {id: 109, name: 'گیالشنگ', stateId: 22},
  {id: 110, name: 'مانگن', stateId: 22},
  {id: 111, name: 'سنگتام', stateId: 22},
  {id: 112, name: 'چنئی', stateId: 23},
  {id: 113, name: 'کوئمبٹور', stateId: 23},
  {id: 114, name: 'مدرائی', stateId: 23},
  {id: 115, name: 'ترچیراپلی', stateId: 23},
  {id: 116, name: 'سالم', stateId: 23},
  {id: 117, name: 'حیدرآباد', stateId: 24},
  {id: 118, name: 'وارنگل', stateId: 24},
  {id: 119, name: 'نظام آباد', stateId: 24},
  {id: 120, name: 'کریم نگر', stateId: 24},
  {id: 121, name: 'خمّم', stateId: 24},
  {id: 122, name: 'آگرتالہ', stateId: 25},
  {id: 123, name: 'اوڈائیپور', stateId: 25},
  {id: 124, name: 'ڈھرمانگر', stateId: 25},
  {id: 125, name: 'بیلونیا', stateId: 25},
  {id: 126, name: 'کیلاسہار', stateId: 25},
  {id: 127, name: 'لاکھنؤ', stateId: 26},
  {id: 128, name: 'کانپور', stateId: 26},
  {id: 129, name: 'غازی آباد', stateId: 26},
  {id: 130, name: 'آگرہ', stateId: 26},
  {id: 131, name: 'وارانسی', stateId: 26},
  {id: 132, name: 'دہرادون', stateId: 27},
  {id: 133, name: 'ہردوار', stateId: 27},
  {id: 134, name: 'رشیکش', stateId: 27},
  {id: 135, name: 'نینیتال', stateId: 27},
  {id: 136, name: 'مسوری', stateId: 27},
  {id: 137, name: 'کولکاتہ', stateId: 28},
  {id: 138, name: 'ہووراہ', stateId: 28},
  {id: 139, name: 'درگاپور', stateId: 28},
  {id: 140, name: 'اسنسول', stateId: 28},
  {id: 141, name: 'سلیگوری', stateId: 28},
];
