export const translation = [
  {
    English: 'Select Language',
    Hindi: 'भाषा चुनें',
    Punjabi: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    Tamil: 'மொழியை தேர்ந்தெடுக்கவும்',
    Urdu: 'زبان منتخب کریں',
  },
  {
    English: 'Cancel',
    Hindi: 'रद्द करें',
    Punjabi: 'ਰੱਦ ਕਰੋ',
    Tamil: 'ரத்து செய்',
    Urdu: 'منسوخ',
  },
  {
    English: 'Apply',
    Hindi: 'लागू करें',
    Punjabi: 'ਲਾਗੂ ਕਰੋ',
    Tamil: 'விண்ணப்பிக்க',
    Urdu: 'لاگو کریں',
  },
  {
    English: 'Today',
    Hindi: 'आज',
    Punjabi: 'ਅੱਜ',
    Tamil: 'இன்று',
    Urdu: 'آج',
  },
  {
    English: 'Tomorrow',
    Hindi: 'कल',
    Punjabi: 'ਕਲ',
    Tamil: 'நாளை',
    Urdu: 'کل',
  },
  {
    English: 'Select Languages',
    Hindi: 'भाषाएं चुनें',
    Punjabi: 'ਭਾਸ਼ੇ ਚੁਣੋ',
    Tamil: 'மொழிகளைத் தேர்ந்தெடுக்க',
    Urdu: 'زبانیں منتخب کریں',
  },
  {
    English: 'Temperature Unit',
    Hindi: 'तापमान इकाई',
    Punjabi: 'ਤਾਪਮਾਨ ਇਕਾਈ',
    Tamil: 'வெப்ப அலகு',
    Urdu: 'درجہ حرارت کی اکائی',
  },
  {
    English: 'Feel Like',
    Hindi: 'महसूस करें',
    Punjabi: 'ਮਹਿਸੂਸ ਕਰੋ',
    Tamil: 'உணர்வு',
    Urdu: 'محسوس کریں',
  },
  {
    English: 'Select your city',
    Hindi: 'अपना शहर चुनें',
    Punjabi: 'ਆਪਣਾ ਸ਼ਹਿਰ ਚੁਣੋ',
    Tamil: 'உங்கள் நகரத்தை தேர்வு செய்க',
    Urdu: 'اپنا شہر منتخب کریں',
  },
  {
    English: 'Close',
    Hindi: 'बंद करें',
    Punjabi: 'ਬੰਦ ਕਰੋ',
    Tamil: 'மூடு',
    Urdu: 'بند کریں',
  },
];
